//ESQUELETO DO QUADRINHO SQUAD
//ORGANIZAÇÃO DO CÓDIGO E PASTAS
//PALETA DE CORES
//+ 1 PONTO PÁGINA A MAIS
//TEMAS: JOALHERIA, AGÊNCIA DE VIAGENS, CLÍNICA NUTRICIONISTA, FLORICULTURA
//PODERÁ CONSULTAR CÓDIGO REALIZADO
//LIBRAS